name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit, composer:v2
          coverage: xdebug3
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: PHPUnit
        run: |
          ./vendor/bin/phpunit --stop-on-failure --coverage-php=coverage.php
        env:
          XDEBUG_MODE: coverage

      - name: Generate Coverage report
        run: |
          php CoverageGenerate.php >> Coverage.md
        env:
          XDEBUG_MODE: coverage

      - name: PHPStan Analysis
        run: |
          ./vendor/bin/phpstan analyse --configuration=phpstan.neon --memory-limit=1024M --error-format=md --no-progress >> 'Static Analysis.md'

      - name: Wiki checkout
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: 'wiki'

      - name: Push
        run: |
          mv Coverage.md wiki
          mv 'Static Analysis.md' wiki
          cd wiki
          ls -la
          git config user.name actions-runner
          git config user.email actions-runner@github.com
          git add .
          git commit -m "Add Coverage and Analysis files" 
          git push
